### ISSUE TITLE
-c does not capture input

### ISSUE THREAD

**Issue by meme** [corellium/sud#1]
For example with Magisk `su`: `su -c echo Hello` prints `Hello`.

However, with `sud`: an error occurs https://github.com/corellium/sud/blob/main/src/su.c#L608. It does not capture the rest of the input as the command.

This can be worked around by quoting the parameters passed to `-c`, like: `su -c "echo Hello"`. However, `sud` should instead have the same behaviour as other existing tools so that applications relying on `su` behaviour don't have to change.

**Comment by strazzere** [comment]
Per our discussion in slack --- this seems like we are essentially introducing a bug to make the output the same as `magisk`.

```sh
diff@larry:~/$ sh -c echo foo

diff@larry:~/$ sh -c 'echo foo'
foo
```

I'm open to accepting a PR into a separate fork to maintain compatibility with other tools that contain the bug, though I don't feel we should make the default behavior for this buggy. Alternatively we could introduce a switch to have it parse this way, however it would not accomplish what you're asking as it would still require you to instrument a change in all your code which interacts with `su` to include that switch.

I'll add this to a future todo list (adding it to a `magisk-compatible-branch`), though if you get to it first I'll gladly accept a patchset and push it to a branch. Or just forking this might be the proper solution.
