### ISSUE TITLE
su_exec context is limited in most of real devices, any  way to avoid that 

### ISSUE THREAD

**Issue by Gunkkk** [corellium/sud#3]

**Comment by strazzere** [comment]
You would need to configure the project to reflect the permissions you want, based on what is allowed on a real device. The contexts used here are specific to corellium devices, which map to root. These might not, or more likely don't, exist on whichever device you are targeting.

**Comment by Gunkkk** [comment]
> You would need to configure the project to reflect the permissions you want, based on what is allowed on a real device. The contexts used here are specific to corellium devices, which map to root. These might not, or more likely don't, exist on whichever device you are targeting.

Thanks  for your reply. Yes, I disable the selinux and  it works. It seems that the SELinux permission of shell to local socket has been limited and patching the selinux may also work.
